project:
  type: website
  output-dir: _site

website:
  title: "Física — CIABA"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - text: Aulas
        menu:
          - aula-01-02-centro-gravidade.qmd

format:
  html:
    theme: [brand, theme.scss]
    toc: true
    toc-title: "Nesta página"
    number-sections: true
    lang: pt-BR
    html-math-method: mathjax
  pdf:
    documentclass: article
    lang: pt-BR
    toc: true
    number-sections: true

execute:
  echo: true
  warning: false
